vendor:
    name:       ahnames
    title:      AHnames
    github:     https://github.com/ahnames
    homepage:   https://ahnames.com/
    email:      support@ahnames.com
    license:    proprietary
    authors:
        hiqsol:
            name:       Andrii Vasyliev
            email:      sol@hiqdev.com
            github:     https://github.com/hiqsol
            homepage:   https://hipanel.com/
        SilverFire:
            name:       Dmitry Naumenko
            email:      d.naumenko.a@gmail.com
            github:     https://github.com/SilverFire
            homepage:   http://silverfire.me/

.php_cs:
    header: |
        {{ config.package.title }}

        @link      {{ config.package.homepage }}
        @package   {{ config.package.name }}
        @license   {{ config.package.license }}
        @copyright Copyright (c) {{ config.package.years }}, {{ config.vendor.titleAndHomepage }}
    fixers:
        header_comment: | # Add, replace or remove header comment
            [
                'header'        => $header,
                'separate'      => 'bottom',
                'location'      => 'after_declare_strict',
                'commentType'   => 'PHPDoc',
            ]
        phpdoc_no_alias_tag:                    |       # No alias PHPDoc tags should be used
            ['replacements' => ['type' => 'var']]
        phpdoc_separation:                      false   # Annotations of a different type are separated by a single blank line
        concat_space:                           |       # Concatenation should be spaced according configuration
            ['spacing' => 'one']
    finder:
        notPath:
            - vendor
            - runtime
            - web/assets

